### ISSUE TITLE
API should be able to query by "tag"

### ISSUE THREAD

**Issue by marioluevanos** [Magical-Threads/8th-mind#1]
When making a request to http://api.8thmind.com/articles/, the API returns all articles.

And we have 3 categories:  `ARTICLES | CHALLENGES | CREATE`. 

So we need to be able to filter the query by the 'articleTag'.

**Comment by technomage** [comment]
I note that you are not using Ember Data relationships in the usual manner, where it will build the url from the relationship and load the child models async as needed.  This would simplify the adapter and allow more operations in Ember Data rather than requiring custom handling.  Please advise if you are open this change.

**Comment by marioluevanos** [comment]
Absolutely Michael. I'm open to the recommended changes. Please proceed.

**Comment by technomage** [comment]
Changes committed, leaving open until the route is used in the front end.

/articles?tag= to get a list of all articles with a given tag.

**Comment by technomage** [comment]
Configuration change made to use local server when working in development mode.  This looks for http://localhost:3000/storage ... for assets, which do not appear to be found there.  Please advise on where images are stored, and I will adjust configs to properly locate them.  I could change images back to api.8thmind.com but then any local work would not be matched to the external assets.

**Comment by marioluevanos** [comment]
https://github.com/Magical-Threads/8th-mind/issues/11#issuecomment-343705061

**Comment by technomage** [comment]
This is now implemented in the UI
